//GET
### 10 Obtener el total del stock actual de productos
GET http://localhost:1234/productos/total
### Obtencion de todos los productos
GET http://localhost:1234/productos
### 6 Obtener el precio de un producto por su ID
GET http://localhost:1234/productos/precio/2
### 7 Obtener el nombre de un producto por su ID
GET http://localhost:1234/productos/nombre/2
### Obtención de un producto específico
GET http://localhost:1234/productos/3
### 1 Obtener el listado completo de usuarios
GET http://localhost:1234/usuarios/
### 2 Obtener los datos de un usuario por ID
GET http://localhost:1234/usuarios/3
### 8 Obtener el teléfono de un usuario por su ID
GET http://localhost:1234/usuarios/telefono/3
### 9 Obtener el nombre de un usuario por su ID
GET http://localhost:1234/usuarios/nombre/1


//POST
### Agregado de un producto nuevo, el body lleva el json con el objeto
POST http://localhost:1234/productos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzdWFyaW8iOiJwYWJsb2FsZWphbmRyb2UiLCJuaXZlbCI6MSwiZXhwIjoxNjk2NTQ2OTA4ODcyLCJpYXQiOjE2OTY1NDY4NDh9.aFKLkTEtex16pRGj4vT1Dde76KyNEXCmxWwabS0uPvo

{
    "nombre": "Caja negra de jugar",
    "precio": 325.00
}

### 3 Incluir nuevo usuario
POST http://localhost:1234/usuarios/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzdWFyaW8iOiJwYWJsb2FsZWphbmRyb2UiLCJuaXZlbCI6MSwiZXhwIjoxNjk2NTQ2OTA4ODcyLCJpYXQiOjE2OTY1NDY4NDh9.aFKLkTEtex16pRGj4vT1Dde76KyNEXCmxWwabS0uPvo

{
  "nombre": "Diego Hojoredondo",
  "edad":28,
  "email": "michimiau@siosi.com",
  "telefono": "+1 323-489-7890"
}

//PATCH
### 4 Modificar un usuario
PATCH http://localhost:1234/usuarios/4
Content-Type: application/json

{
  "nombre": "Cara Clarinetes"
}
### Actualización de un producto, el body lleva solo el atributo a modificar
PATCH http://localhost:1234/productos/10
Content-Type: application/json

{
    "nombre": "Mixer multiuso ACME PODEROSO"
}

//DELETE
### Borrado de un producto
DELETE http://localhost:1234/productos/3
### 5 Borrar usuario
DELETE http://localhost:1234/usuarios/4
### Request desde el formulario de logueo en el frontend
POST http://localhost:1234/auth
Content-Type: application/json

    {
        "usuario": "clarapocaluz",
        "password": "clarapass"
    }



